### ISSUE TITLE
The project name is confusing

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-parent#1]
The defacto standard name for projects such as these is `*-parent`. I find the `*-archetype` to be confusing because it makes me think of a maven archetype which creates new project instances. This is just a common parent pom.

I also would like to use this for `cucumber-jvm` so the `*-module-*` is overly specific too.  So can I rename it to `cucumber-parent`?

**Comment by aslakhellesoy** [comment]
Please do - thanks!

**Comment by mlvandijk** [comment]
Looks like this was done ;)
