### ISSUE TITLE
Rename to cucumber-jvm-parent

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-parent#35]
### 🤔 What's the problem you've observed?

It's slightly confusing that this repo isn't namespaced with `cucumber-jvm`.

### ✨ Do you have a proposal for making it better?

Rename it to `cucumber-jvm-parent`

**Comment by mpkorstanje** [comment]
It is used as the parent pom for all java components. Not just cucumber-jvm.

**Comment by mattwynne** [comment]
I was only suggesting renaming the repo, not the artefact. But if it doesn't make sense then let's not.
