### ISSUE TITLE
Upgrade source and target from 1.7 to 1.8

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-parent#4]
Java 7 reached EoL in [April 2015](https://www.infoq.com/news/2015/05/Oracle-Ends-Java-7Public-Updates). I'm not too familiar with Android's current Java 8 support - [here](https://jakewharton.com/androids-java-8-support/) is a relatively recent writeup.

Not being able to use Java 8 language features is pretty frustragting. What would be the consequences of upgrading?

/cc @mpkorstanje

**Comment by mpkorstanje** [comment]
It's a breaking change. But we can pick it up with Cucumber v5 which will upgrade to Java 8.

**Comment by mpkorstanje** [comment]
Cucumber v5 is just about ready btw. I needs some test driving mostly to ensure we place nicely with modules.

**Comment by mpkorstanje** [comment]
Done by 5a74c55e61d08dd025567618f3f411936a8febac.
