### ISSUE TITLE
Fix automated release

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-parent#5]
For 1.0.6 @vincent-psarga and I added b60d5476f5f85bf272fe595efc86bfeffc504b1f to work around an issue where GPG wasn't pick up the passphrase. This only happens on GPG 2.1+, which is what the new CircleCI monorepo build is using.

This fixed the CircleCI monorepo build, but it also broke the TravisCI automated release of this package. I worked around that by doing a manual release:

```
mvn release:clean release:prepare -DautoVersionSubmodules=true -Darguments="-DskipTests=true"
git pull
git checkout v1.0.6
export CI_SONATYPE_PASSWORD="xxxxxxx"
export CI_GPG_PASSPHRASE="xxxxxxxxx"
./scripts/mvn_deploy.sh
```

Since we're moving from TravisCI to CircleCI I wonder if it would make more sense to import this repo into the monorepo where it can take advantage of the tried and tested automated release process we have there.

/cc @mpkorstanje @vincent-psarga

**Comment by mpkorstanje** [comment]
No objections. Do I have sufficient credentials on the circle-ci project to maintain and edit it?

**Comment by mpkorstanje** [comment]
@aslakhellesoy I just closed off cucumber v4. Is this running in Circle CI yet?

**Comment by aslakhellesoy** [comment]
> Do I have sufficient credentials on the circle-ci project to maintain and edit it?

You should - CircleCi piggybacks GitHub’s permissions.

> Is this running in Circle CI yet?

Not yet, feel free to set it up of you feel like it - would be great!

**Comment by mpkorstanje** [comment]
Cheers.

Had a look. Looks like this will take more time then I'd like to spend on it right now. I am going to finish what I started before starting something new. So for now I added an extra profile to work on Travis in https://github.com/cucumber/cucumber-parent/commit/3b9c7a06947912a4aeecfd1e66b6c7197805ec7b.
